// SPDX-License-Identifier: Apache-2.0

using System.Linq;
using CsCheck;
using Xunit;

namespace H3.NET.Native.Tests.Properties;

/// <summary>
/// Property invariants for the hierarchy surface. Valid cells are generated by binning a
/// random in-domain point at a random resolution (matching the other property suites);
/// the high-entropy invalid generator mirrors <see cref="InspectionPropertyTests"/> and
/// asserts a typed-throw-or-graceful-return contract (never a process crash).
/// </summary>
public sealed class HierarchyPropertyTests
{
    private const long Iterations = 100;

    /// <summary>High-entropy invalid-index generator, identical in spirit to the inspection suite.</summary>
    private static readonly Gen<ulong> InvalidIndexGen =
        Gen.Frequency((9, Gen.ULong), (1, Gen.ULong[1UL, 0xFUL]))
            .Where(v => !new H3Index(v).IsValidCell());

    [Fact]
    public void CellToChildren_HasExpectedSize_AndEveryChildMapsBackToParent()
    {
        // A valid cell at res r, refined to a generated childRes in [r, r+5]. The delta is
        // capped: at 7 children per level, r+5 stays well under Array.MaxLength, while a
        // larger span (e.g. res-0 -> res-15) would legitimately trip the binding's
        // Array.MaxLength guard (ArgumentOutOfRangeException), which is a separate contract.
        var gen = Generators.LatLngGen
            .Select(Generators.Resolution, (p, r) => (p, r))
            .SelectMany(pr => Gen.Int[pr.r, System.Math.Min(15, pr.r + 5)]
                .Select(childRes => (pr.p, pr.r, childRes)));

        gen.Sample(
            input =>
            {
                var (point, res, childRes) = input;
                var cell = H3Index.FromLatLng(point, res);

                var children = cell.CellToChildren(childRes);
                long maxSize = cell.CellToChildrenSize(childRes);

                // The stripped result never exceeds the upstream size. Exact equality does
                // NOT hold even for a hexagon parent: a hexagon can contain a pentagon
                // DESCENDANT several levels down, which strips H3_NULL slots and yields
                // fewer than 7^delta. Equality is only guaranteed when no pentagon appears
                // anywhere in the subtree, so the robust invariant is <= maxSize.
                Assert.True(children.Length <= maxSize);
                Assert.True(children.Length > 0);

                Assert.All(children, child => Assert.Equal(cell.Value, child.CellToParent(res).Value));
            },
            iter: Iterations);
    }

    [Fact]
    public void CompactThenUncompact_IsSetStable()
    {
        // Generate a parent and a child resolution at most 3 finer (keeps the set small).
        var gen = Generators.LatLngGen
            .Select(Generators.Resolution, (p, r) => (p, r))
            .SelectMany(pr => Gen.Int[pr.r, System.Math.Min(15, pr.r + 3)]
                .Select(childRes => (pr.p, pr.r, childRes)));

        gen.Sample(
            input =>
            {
                var (point, res, childRes) = input;
                var cell = H3Index.FromLatLng(point, res);
                var children = cell.CellToChildren(childRes);

                var compacted = H3Index.CompactCells(children);
                var roundTripped = H3Index.UncompactCells(compacted, childRes);

                Assert.Equal(
                    children.Select(c => c.Value).ToHashSet(),
                    roundTripped.Select(c => c.Value).ToHashSet());
            },
            iter: Iterations);
    }

    [Fact]
    public void CellToParent_OnInvalidIndex_ThrowsTyped_OrReturns()
    {
        InvalidIndexGen.Sample(
            raw =>
            {
                var cell = new H3Index(raw);
                try
                {
                    _ = cell.CellToParent(0);
                }
                catch (H3Exception)
                {
                    // Typed, graceful failure is acceptable.
                }
            },
            iter: Iterations);
    }

    [Fact]
    public void CellToChildren_OnInvalidIndex_ThrowsTyped_OrReturns()
    {
        // childRes is kept small ([0, 3]): a junk index can report a colossal (but still
        // < Array.MaxLength) cellToChildrenSize at deep resolutions, which would allocate
        // many GB per iteration and thrash the host. The contract under test is "typed
        // throw or graceful return, never a process crash", not allocation stress, so a
        // shallow childRes exercises the same native size + fill + strip path safely.
        var gen = InvalidIndexGen.Select(Gen.Int[0, 3], (raw, childRes) => (raw, childRes));
        gen.Sample(
            input =>
            {
                var (raw, childRes) = input;
                var cell = new H3Index(raw);
                try
                {
                    _ = cell.CellToChildren(childRes);
                }
                catch (H3Exception)
                {
                    // Typed, graceful failure is acceptable.
                }
                catch (System.ArgumentOutOfRangeException)
                {
                    // A junk index can report an absurd cellToChildrenSize that overflows
                    // Array.MaxLength; the binding guards that as ArgumentOutOfRangeException.
                }
            },
            iter: Iterations);
    }
}
